[colors.bright]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.normal]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.primary]
background = "0x2c2e34"
foreground = "0xc5cdd9"

[font]
size = 11.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.offset]
x = 0
y = 0

[schemes.edge_dark_aura.bright]
black = "0x363a49"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_aura.normal]
black = "0x363a49"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_aura.primary]
background = "0x2b2d37"
foreground = "0xc5cdd9"

[schemes.edge_dark_def.bright]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_def.normal]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_def.primary]
background = "0x2c2e34"
foreground = "0xc5cdd9"

[schemes.edge_dark_neon.bright]
black = "0x363a4e"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_neon.normal]
black = "0x363a4e"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[schemes.edge_dark_neon.primary]
background = "0x2b2d3a"
foreground = "0xc5cdd9"

[schemes.edge_light.bright]
black = "0x4b505b"
blue = "0x5079be"
cyan = "0x3a8b84"
green = "0x608e32"
magenta = "0xb05ccc"
red = "0xd05858"
white = "0xfafafa"
yellow = "0xbe7e05"

[schemes.edge_light.normal]
black = "0x4b505b"
blue = "0x5079be"
cyan = "0x3a8b84"
green = "0x608e32"
magenta = "0xb05ccc"
red = "0xd05858"
white = "0xfafafa"
yellow = "0xbe7e05"

[schemes.edge_light.primary]
background = "0xfafafa"
foreground = "0x4b505b"

[window.padding]
x = 4
y = 4
