general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono NL"

[font.offset]
x = 0
y = 0

[window.padding]
x = 4
y = 4

[env]
TERM = "xterm-256color"
