call plug#begin()

Plug 'joshdick/onedark.vim'

call plug#end()

set number
set nowrap
set hidden
set shortmess+=I
set fillchars=eob:\ 
set ttimeout
set ttimeoutlen=1
set ttyfast
set tabstop=2
set shiftwidth=2
set expandtab
set noswapfile

syntax on
colorscheme onedark

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

let mapleader = " "

nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>bn :bnext<cr>
nnoremap <leader>bp :bprevious<cr>

inoremap jk <esc>
