call plug#begin()

Plug 'joshdick/onedark.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'airblade/vim-gitgutter'

call plug#end()

set number
set nowrap
set hidden
set shortmess+=I
set fillchars=eob:\ 
set ttimeout
set ttimeoutlen=1
set ttyfast
set tabstop=2
set shiftwidth=2
set expandtab
set noswapfile
set splitright
set splitbelow
set cursorline
set incsearch
set ignorecase
set smartcase
set clipboard=unnamed
set mouse=a
set signcolumn=yes
set updatetime=100

syntax on
colorscheme onedark

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

let mapleader = " "

nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>
nnoremap <leader>f :Files<cr>
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>e :NERDTreeToggle<cr>
nnoremap <leader>u :PlugUpdate<cr>

nnoremap <c-h> :wincmd h<cr>
nnoremap <c-j> :wincmd j<cr>
nnoremap <c-k> :wincmd k<cr>
nnoremap <c-l> :wincmd l<cr>

inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>

let g:fzf_vim = {}
let g:fzf_preview_window = []
