#! /bin/sh

export GTK_THEME=Adwaita:dark

xsetroot -cursor_name left_ptr
#hsetroot -solid "#000000"

pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x light-locker > /dev/null || light-locker &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       false

bspc config focus_follows_pointer true

bspc rule -a feh state=floating
bspc rule -a Emacs state=tiled
