#! /bin/sh

#export GTK_THEME=Adwaita:dark

#export XSECURELOCK_SAVER=saver_blank
#export XSECURELOCK_BACKGROUND_COLOR="#000000"
#export XSECURELOCK_AUTH_BACKGROUND_COLOR="#000000"
#export XSECURELOCK_FONT="MesloLGS Nerd Font Mono"
#export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
#export XSECURELOCK_COMPOSITE_OBSCURER=0
#export XSECURELOCK_NO_COMPOSITE=1

xsetroot -cursor_name left_ptr
#hsetroot -solid "#000000"

pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x polybar > /dev/null || polybar &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           0
#bspc config top_padding          23

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       false

bspc config focus_follows_pointer true

#bspc rule -a feh state=floating
#bspc rule -a Emacs state=tiled

#xset s 300 5
#xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
