#! /bin/sh

xsetroot -cursor_name left_ptr
hsetroot -solid "#000000"

export GTK_THEME=Adwaita:dark

export XSECURELOCK_SAVER=saver_blank
export XSECURELOCK_BACKGROUND_COLOR="#000000"
export XSECURELOCK_AUTH_BACKGROUND_COLOR="#000000"
export XSECURELOCK_FONT="CaskaydiaCove Nerd Font"
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_COMPOSITE_OBSCURER=0
export XSECURELOCK_NO_COMPOSITE=1

xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

exec dbus-launch --sh-syntax --exit-with-session bspwm
