export PATH=/opt/homebrew/bin:$PATH
export PATH=~/go/bin:$PATH
export PATH=/usr/local/opt/bison/bin:/opt/homebrew/opt/bison/bin:$PATH
export PATH=/usr/local/bin/llama:$PATH

autoload -Uz compinit && compinit

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ];
then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

eval "$(direnv hook zsh)"
